### ISSUE TITLE
Deprecated functions used in WordpressApi from AFNetworking framework

### ISSUE THREAD

**Issue by ocastx** [wordpress-mobile/WordPress-API-iOS#9]
![bildschirmfoto 2013-11-11 um 16 22 26](https://f.cloud.github.com/assets/2399622/1513665/3a2e1e72-4ae6-11e3-8659-1b4fcdd716d9.png)

I get this error when I build my project. I read that the function "setAuthenticationChallengeBlock" is deprecated with the new commit of AFNetwork framework.

**Comment by SergioEstevao** [comment]
AFNetworking is now update to 2.6.3 so this issue is solved.
